WebProje/Controllers/UyelikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProje.Data;
using WebProje.Models;

namespace WebProje.Controllers
{
    public class UyelikController : Controller
    {
        public ActionResult YeniUyelik()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniUyelik(Uye model, string textBoxDogum, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (String.IsNullOrEmpty(textBoxDogum))
            {
                ModelState.AddModelError("textBoxDogum", "Doğum tarihi boş geçilemez");
                return View();
            }

            int yil = int.Parse(textBoxDogum.Substring(6));

            if (yil > 2002)
            {
                ModelState.AddModelError("textBoxDogum", "Yaşınız 12 den küçük olamaz");
                return View();
            }

            Uye uye = new Uye();
            if (file != null)
            {
                file.SaveAs(Server.MapPath("~/Images/") + file.FileName);
                uye.uyeResim = "/Images/" + file.FileName;
            }

            uye.uyeAd = model.uyeAd;
            uye.EPosta = model.EPosta;
            uye.uyeSoyad = model.uyeSoyad;
            uye.UyeOlmaTarih = DateTime.Now;
            uye.Sifre = model.Sifre;

            using (WebProjeContext vt = new WebProjeContext())
            {
                vt.Uyes.Add(uye);
                vt.SaveChanges();
                return RedirectToAction("Anasayfa","Home");
            }
        }

        public ActionResult Giris()
        {
            return View();
        }

        [HttpPost]
        public string UyeGiris()
        {

            string posta = Request.Form["txtPosta"];
            string sifre = Request.Form["pswSifre"];
            if (String.IsNullOrEmpty(posta) && String.IsNullOrEmpty(sifre))
            {
                return "E-Posta adresinizi ve şifrenizi girmediniz.";
            }
            else if (String.IsNullOrEmpty(posta))
            {
                return "E-posta adresinizi girmediniz.";
            }
            else if (string.IsNullOrEmpty(sifre))
            {
                return "Şifrenizi girmediniz.";
            }
            else
            {
                using (WebProjeContext db = new WebProjeContext())
                {
                    var uye = (from i in db.Uyes where i.Sifre == sifre && i.EPosta == posta select i).SingleOrDefault();
                    
                    if (uye == null) return "Kullanıcı adınızı ya da şifreyi hatalı girdiniz.";

                    Session["uyeAd"] = uye.uyeAd;
                    if(uye.Yetki!=null)
                    Session["yetki"] = uye.Yetki.yetkiAdi;

                    return "Sisteme, başarıyla giriş yaptınız.<script type='text/javascript'>setTimeout(function(){window.location='/Home/Anasayfa'},1000);</script>";
                }
            }
        }

        public ActionResult Cikis()
        {
            Session.Clear();
            return RedirectToAction("Anasayfa","Home");
        }
    }
}

WebProje/Views/Uyelik/Giris.cshtml
@{
    ViewBag.Title = "Giris";
}

@section scripts{
    <style type="text/css">
        #formKapsayici {
            box-shadow: 0 0 5px gray;
            padding: 25px;
            height: 500px;
        }

        #divSol, #divSag {
            float: left;
            margin-left: 25px;
            color:antiquewhite;
        }

            #divSol *, #divSag * {
                margin-top: 15px;
            }

        input[type="text"] {
            width: 250px;
        }

        #btnGiris {
            clear: both;
            display: block;
            margin-left: 176px;
        }

        #divSonuc {
            color: red;
        }
    </style>
}
@using (Ajax.BeginForm("UyeGiris", "Uyelik", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divSonuc" }, new { id = "formKapsayici" }))
{
    <div id="divSol">
        @Html.Label("E-Posta Adresiniz")<br />
        @Html.Label("Şifreniz")
    </div>
    <div id="divSag">
        : @Html.TextBox("txtPosta")<br />
        : @Html.Password("pswSifre")
    </div>
    <input type="submit" value="Giriş" id="btnGiris" />
    <div id="divSonuc"></div>
}

WebProje/Views/Uyelik/YeniUyelik.cshtml
@model WebProje.Data.Uye

@{
    ViewBag.Title = "YeniUyelik";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <style type="text/css">
        #formKapsayici {
            box-shadow: 0 0 5px gray;
            padding: 25px;
            height: 500px;
        }

        #divSol, #divSag {
            float: left;
            margin-left: 25px;
        }

            #divSol *, #divSag * {
                margin-top: 15px;
            }
            #divSol{
                color:antiquewhite;
            }

        input[type="text"] {
            width: 250px;
        }

        #btnUyeOl {
            clear: both;
            display: block;
            margin-left: 170px;
        }
    </style>

    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#textBoxDogum").datepicker();
        });
    </script>
}
@using (Html.BeginForm("YeniUyelik", "Uyelik", FormMethod.Post, new { enctype = "multipart/form-data", id = "formKapsayici" }))
{
    <div id="divSol">
        @Html.LabelFor(i => Model.uyeAd)<br /><br />
        @Html.LabelFor(i => Model.uyeSoyad)<br /><br />
        @Html.LabelFor(i => Model.EPosta)<br /><br />
        @Html.LabelFor(i => Model.Sifre)<br /><br />
        @Html.Label("Doğum Tarihiniz")<br /><br />
        @Html.Label("Profil Resminiz")<br /><br />
    </div>
    <div id="divSag">
        : @Html.TextBoxFor(i => Model.uyeAd)<br /><br />
        : @Html.TextBoxFor(i => Model.uyeSoyad)<br /><br />
        : @Html.TextBoxFor(i => Model.EPosta)<br /><br />
        : @Html.TextBoxFor(i => Model.Sifre)<br /><br />
        : @Html.TextBox("textBoxDogum")<br /><br />

        <input type="file" id="inputFile" name="file" /> <br /><br />

    </div>
    <input type="submit" value="Giriş" id="btnUyeOl" />
    
    @Html.ValidationSummary()
}