WebProje/Controllers/CRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProje.Data;

namespace WebProje.Controllers
{
    public class CRUDController : Controller
    {
        WebProjeContext vt = new WebProjeContext();

        public ActionResult Detay()
        {
            List<Yorum> yorumListe = vt.Yorums.OrderByDescending(x => x.yorumTarih).ToList();
            return PartialView(yorumListe);
        }
    }
}

WebProje/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebProje.Data;

namespace WebProje.Controllers
{
    public class HomeController : Controller
    {
        Uye uye;
        WebProjeContext vt = new WebProjeContext();

        public ActionResult Anasayfa()
        {
            List<Kitap> kitapListe = vt.Kitaps.OrderByDescending(x => x.kitapTarih).Take(10).ToList();
            return PartialView(kitapListe);
        }
        
        public ActionResult Hakkimizda()
        {
            return View();
        }

        public ActionResult Iletisim()
        {
            return View();
        }
        
        public ActionResult PuanKatalogu()
        {
            return View();
        }
        
        public ActionResult Arama(string aranan)
        {
            List<Kitap> aramaListesi = vt.Kitaps.ToList();

            if (!String.IsNullOrEmpty(aranan))
            {
                aramaListesi = vt.Kitaps.Where(x => x.kitapAd.Contains(aranan)).ToList();
            }

            return PartialView(aramaListesi);
        }
        
        public ActionResult Roman()
        {
            List<Kitap> romanListesi = vt.Kitaps.Where(x => x.kategori == "Roman").ToList();
            return PartialView(romanListesi);
        }

        public ActionResult Oyku()
        {
            List<Kitap> oykuListesi = vt.Kitaps.Where(x => x.kategori == "Öykü").ToList();
            return PartialView(oykuListesi);
        }

        public ActionResult Siir()
        {
            List<Kitap> siirListesi = vt.Kitaps.Where(x => x.kategori == "Şiir").ToList();
            return PartialView(siirListesi);
        }

        public ActionResult Deneme()
        {
            List<Kitap> denemeListesi = vt.Kitaps.Where(x => x.kategori == "Deneme").ToList();
            return PartialView(denemeListesi);
        }

        public ActionResult Ani()
        {
            List<Kitap> aniListesi = vt.Kitaps.Where(x => x.kategori == "Anı").ToList();
            return PartialView(aniListesi);
        }

        public ActionResult GeziYazisi()
        {
            List<Kitap> geziListesi = vt.Kitaps.Where(x => x.kategori == "Gezi Yazısı").ToList();
            return PartialView(geziListesi);
        }

        public ActionResult CizgiRoman()
        {
            List<Kitap> cizgiListesi = vt.Kitaps.Where(x => x.kategori == "Çizgi Roman").ToList();
            return PartialView(cizgiListesi);
        }

        public ActionResult Arastirma()
        {
            List<Kitap> arastirmaListesi = vt.Kitaps.Where(x => x.kategori == "Araştırma" || x.kategori == "Tarih").ToList();
            return PartialView(arastirmaListesi);
        }


        public ActionResult ChangeCulture(string lang, string returnUrl)
        {
            Session["Culture"] = new CultureInfo(lang);
            return Redirect(returnUrl);
        }
    }
}

WebProje/Views/Home/Anasayfa.cshtml
@model IEnumerable<WebProje.Data.Kitap>

@{
    ViewBag.Title = "Anasayfa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <div class="col-md-2" style="background-color: #151c22">
                            <p class="lead" style="color:#f6ddb0">@Resources.lang.Kategoriler</p>
                            <div class="list-group">
                                <a href="/Home/Roman" class="list-group-item">@Resources.lang.Roman</a>
                                <a href="/Home/Oyku" class="list-group-item">@Resources.lang.Öykü</a>
                                <a href="/Home/Siir" class="list-group-item">@Resources.lang.Şiir</a>
                                <a href="/Home/Deneme" class="list-group-item">@Resources.lang.Deneme</a>
                                <a href="/Home/Ani" class="list-group-item">@Resources.lang.Anı</a>
                                <a href="/Home/GeziYazisi" class="list-group-item">@Resources.lang.Gezi_Yazısı</a>
                                <a href="/Home/CizgiRoman" class="list-group-item">@Resources.lang.Çizgi_Roman</a>
                                <a href="/Home/Arastirma" class="list-group-item">@Resources.lang.Araştırma_Tarih</a>
                            </div>
                        </div>


                        <div class="col-md-9">
                            <div class="row carousel-holder">
                                <div class="col-md-12">
                                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                        <ol class="carousel-indicators">
                                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                        </ol>
                                        <div class="carousel-inner">
                                            <div class="item active">
                                                <img class="slide-image" src="~/Images/slide-1.jpg" alt="">
                                            </div>
                                            <div class="item">
                                                <img class="slide-image" src="~/Images/slide-2.jpg" alt="">
                                            </div>
                                            <div class="item">
                                                <img class="slide-image" src="~/Images/slide-3.jpg" alt="">
                                            </div>
                                        </div>
                                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                            <span class="glyphicon glyphicon-chevron-left"></span>
                                        </a>
                                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                            <span class="glyphicon glyphicon-chevron-right"></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <h2 style="color:#f6ddb0">@Resources.lang.Son_Eklenenler</h2>
                            <table class="table" border="1" style="background-color:#428bca">
                                <tr>
                                    <th style="color:#f6ddb0">
                                        <center>@Resources.lang.Kitabın_Adı</center>
                                    </th>
                                    <th style="color:#f6ddb0">
                                        <center>@Resources.lang.Kitabın_Yazarı</center>
                                    </th>
                                    <th style="color:#f6ddb0">
                                        <center>@Resources.lang.Çıkış_Tarihi</center>
                                    </th>
                                    <th style="color:#f6ddb0"></th>
                                </tr>
                                @foreach (var item in Model)
                                {
                                    <tr style="background-color:#151c22">
                                        <td style="color:#f6ddb0">
                                            @Html.DisplayFor(modelItem => item.kitapAd)
                                        </td>
                                        <td style="color:#f6ddb0">
                                            @Html.DisplayFor(modelItem => item.kitapYazar)
                                        </td>
                                        <td style="color:#f6ddb0">
                                            @Html.DisplayFor(modelItem => item.kitapTarih)
                                        </td>
                                        <td>
                                            @Html.ActionLink(Resources.lang.Detay, "Detay", "CRUD")
                                        </td>
                                    </tr>
                                }
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

WebProje/Views/Home/Ani.cshtml
@model IEnumerable<WebProje.Data.Kitap>

@{
    ViewBag.Title = "Ani";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body>
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12" style="background-color:#428bca">
                    <hr>
                    <h2 class="intro-text text-center" style="color:rgb(224,68,65)">
                        <strong style="color:#f6ddb0">@Resources.lang.Anı</strong>
                    </h2>
                    <hr>
                </div>
                <table class="table" border="1" style="background-color:#428bca">
                    <tr>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Adı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Yazarı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Çıkış_Tarihi</center>
                        </th>
                        <th style="color:#f6ddb0"></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr style="background-color:#151c22">
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapAd)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapYazar)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapTarih)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.kitapID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.kitapID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.kitapID })
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</body>

WebProje/Views/Home/Arama.cshtml
@model IEnumerable<WebProje.Data.Kitap>

@{
    ViewBag.Title = "Arama";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Arama</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.kitapAd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kitapYazar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kategori)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kitapTarih)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kitapResim)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.kitapAd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kitapYazar)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kategori)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kitapTarih)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kitapResim)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.kitapID }) |
            @Html.ActionLink("Details", "Details", new { id=item.kitapID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.kitapID })
        </td>
    </tr>
}

</table>

WebProje/Views/Home/Arastirma.cshtml
@model IEnumerable<WebProje.Data.Kitap>

@{
    ViewBag.Title = "Arastirma";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body>
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12" style="background-color:#428bca">
                    <hr>
                    <h2 class="intro-text text-center" style="color:rgb(224,68,65)">
                        <strong style="color:#f6ddb0">@Resources.lang.Araştırma_Tarih</strong>
                    </h2>
                    <hr>
                </div>
                <table class="table" border="1" style="background-color:#428bca">
                    <tr>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Adı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Yazarı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Çıkış_Tarihi</center>
                        </th>
                        <th style="color:#f6ddb0"></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr style="background-color:#151c22">
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapAd)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapYazar)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapTarih)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.kitapID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.kitapID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.kitapID })
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</body>

WebProje/Views/Home/CizgiRoman.cshtml
@model IEnumerable<WebProje.Data.Kitap>

@{
    ViewBag.Title = "CizgiRoman";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body>
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12" style="background-color:#428bca">
                    <hr>
                    <h2 class="intro-text text-center" style="color:rgb(224,68,65)">
                        <strong style="color:#f6ddb0">@Resources.lang.Çizgi_Roman</strong>
                    </h2>
                    <hr>
                </div>
                <table class="table" border="1" style="background-color:#428bca">
                    <tr>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Adı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Yazarı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Çıkış_Tarihi</center>
                        </th>
                        <th style="color:#f6ddb0"></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr style="background-color:#151c22">
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapAd)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapYazar)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapTarih)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.kitapID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.kitapID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.kitapID })
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</body>

WebProje/Views/Home/Deneme.cshtml
@model IEnumerable<WebProje.Data.Kitap>

@{
    ViewBag.Title = "Deneme";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body>
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12" style="background-color:#428bca">
                    <hr>
                    <h2 class="intro-text text-center" style="color:rgb(224,68,65)">
                        <strong style="color:#f6ddb0">@Resources.lang.Deneme</strong>
                    </h2>
                    <hr>
                </div>
                <table class="table" border="1" style="background-color:#428bca">
                    <tr>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Adı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Yazarı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Çıkış_Tarihi</center>
                        </th>
                        <th style="color:#f6ddb0"></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr style="background-color:#151c22">
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapAd)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapYazar)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapTarih)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.kitapID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.kitapID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.kitapID })
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</body>

WebProje/Views/Home/GeziYazisi.cshtml
@model IEnumerable<WebProje.Data.Kitap>

@{
    ViewBag.Title = "GeziYazisi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body>
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12" style="background-color:#428bca">
                    <hr>
                    <h2 class="intro-text text-center" style="color:rgb(224,68,65)">
                        <strong style="color:#f6ddb0">@Resources.lang.Gezi_Yazısı</strong>
                    </h2>
                    <hr>
                </div>
                <table class="table" border="1" style="background-color:#428bca">
                    <tr>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Adı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Yazarı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Çıkış_Tarihi</center>
                        </th>
                        <th style="color:#f6ddb0"></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr style="background-color:#151c22">
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapAd)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapYazar)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapTarih)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.kitapID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.kitapID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.kitapID })
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</body>

WebProje/Views/Home/Hakkimizda.cshtml
@{
    ViewBag.Title = "Hakkimizda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12" style="background-color:whitesmoke">
                    <hr>
                    <h2 class="intro-text text-center" style="color:rgb(224,68,65)">
                        <strong>@Resources.lang.Hakkımızda</strong>
                    </h2>
                    <hr>
                </div>
                <div class="col-md-6">
                    <img class="img-responsive img-border-left" src="~/Images/slide-2.jpg" alt="">
                </div>
                <div class="col-md-6" style="background-color:whitesmoke">
                    <h2> </h2>
                    <p><strong style="color:rgb(224,68,65)">"Ne Okumalı", 2016 yılında kurulmuş olan bir kitap eleştiri sitesidir.</strong></p>
                    <p><strong style="color:rgb(224,68,65)">Bu site kapsamında, dilediğiniz kitabı özgürce eleştirebilir, kitap okumak isteyenlere yardımcı olabilirsiniz.</strong></p>
                    <p><strong style="color:rgb(224,68,65)">Üslubunuzu koruduğunuz müddetçe eleştirinizin daha sağlıklı olacağına inandığımızdan, uygunsuz bulunan içerikler yayınlanmayacaktır. Yapacağınız eleştirilerin uygunsuz olmaması kadar yapıcı olması da önem arz etmektedir.</strong></p>
                    <p><strong style="color:rgb(224,68,65)">İyi vakit geçirmeniz dileğiyle...</strong></p>
                    <h2 style="color:rgb(224,68,65)">"Ne Okumalı" Ekibi</h2>
                    <h2> </h2>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</body>

WebProje/Views/Home/Iletisim.cshtml
@{
    ViewBag.Title = "Iletisim";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="box">
            <div class="col-lg-12" style="background-color:whitesmoke">
                <hr>
                <h2 class="intro-text text-center" style="color:#FF9800">
                    <strong>İletişim Formu</strong>
                </h2>
                <hr>
            </div>
        </div>
    </div>
</div>

<body>
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12" style="background-image:inherit">
                    <center>
                        <form role="form">
                            <div class="row">
                                <div class="form-group col-md-20">

                                    <label style="color:#FF9800">@Resources.lang.Adınız</label>

                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-15">

                                    <label style="color:#FF9800">@Resources.lang.Soyadınız</label>

                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-15">

                                    <label style="color:#FF9800">@Resources.lang.E_Posta_Adresiniz</label>

                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="form-group col-lg-15">
                                <label style="color:#FF9800">@Resources.lang.Mesajınız</label>
                                <textarea class="form-control" rows="6"></textarea>
                            </div>
                            <div class="form-group col-lg-15">
                                <input type="hidden" name="save" value="contact">
                                <button type="submit" class="btn btn-default" style="color:#FF9800">@Resources.lang.Gönder</button>
                            </div>
                        </form>
                    </center>
                </div>
            </div>
        </div>
    </div>
</body>

WebProje/Views/Home/Oyku.cshtml
@model IEnumerable<WebProje.Data.Kitap>

@{
    ViewBag.Title = "Oyku";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<body>
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="col-lg-12" style="background-color:#428bca">
                    <hr>
                    <h2 class="intro-text text-center" style="color:rgb(224,68,65)">
                        <strong style="color:#f6ddb0">@Resources.lang.Öykü</strong>
                    </h2>
                    <hr>
                </div>
                <table class="table" border="1" style="background-color:#428bca">
                    <tr>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Adı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Kitabın_Yazarı</center>
                        </th>
                        <th style="color:#f6ddb0">
                            <center>@Resources.lang.Çıkış_Tarihi</center>
                        </th>
                        <th style="color:#f6ddb0"></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr style="background-color:#151c22">
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapAd)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapYazar)
                            </td>
                            <td style="color:#f6ddb0">
                                @Html.DisplayFor(modelItem => item.kitapTarih)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.kitapID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.kitapID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.kitapID })
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</body>